/* Auto-generated from catppuccin zed-icons (Mocha theme mapping).
   Do not edit by hand — see tools/gen_icons.zig (`zig build gen-icons`). */
#ifndef ZC_ICON_DATA_H
#define ZC_ICON_DATA_H

typedef struct { const char *key; const char *icon; } ZcIconKV;
typedef struct { const char *key; const char *collapsed; const char *expanded; } ZcIconDir;

static const ZcIconKV zc_stems[] = {
    { ".DS_Store", "macos" },
    { "CMakeLists.txt", "cmake" },
    { "Caddyfile", "caddy" },
    { "Cargo.lock", "cargo-lock" },
    { "Cargo.toml", "cargo" },
    { "LICENSE", "license" },
    { "Makefile", "makefile" },
    { "README", "readme" },
    { "README.md", "readme" },
    { "README.txt", "readme" },
};
static const int zc_stems_n = 10;

static const ZcIconKV zc_suffixes[] = {
    { "._sc_", "godot-assets" },
    { ".adonisrc.json", "adonis" },
    { ".alexrc", "alex" },
    { ".alexrc.js", "alex" },
    { ".alexrc.yaml", "alex" },
    { ".alexrc.yml", "alex" },
    { ".angular-cli.json", "angular" },
    { ".ansible-lint", "ansible-lint" },
    { ".babel-plugin-macrosrc", "babel" },
    { ".babel-plugin-macrosrc.js", "babel" },
    { ".babel-plugin-macrosrc.json", "babel" },
    { ".babel-plugin-macrosrc.yaml", "babel" },
    { ".babel-plugin-macrosrc.yml", "babel" },
    { ".babelrc", "babel" },
    { ".babelrc.cjs", "babel" },
    { ".babelrc.js", "babel" },
    { ".babelrc.json", "babel" },
    { ".babelrc.mjs", "babel" },
    { ".bazelrc", "bazel" },
    { ".blitz.config.compiled.js", "blitz" },
    { ".bowerrc", "bower" },
    { ".browserslistrc", "browserslist" },
    { ".codeclimate.yml", "code-climate" },
    { ".commitlint.yaml", "commitlint" },
    { ".commitlint.yml", "commitlint" },
    { ".commitlintrc", "commitlint" },
    { ".commitlintrc.cjs", "commitlint" },
    { ".commitlintrc.cts", "commitlint" },
    { ".commitlintrc.js", "commitlint" },
    { ".commitlintrc.json", "commitlint" },
    { ".commitlintrc.ts", "commitlint" },
    { ".commitlintrc.yaml", "commitlint" },
    { ".commitlintrc.yml", "commitlint" },
    { ".cspell.json", "cspell" },
    { ".cspell.yaml", "cspell" },
    { ".cspell.yml", "cspell" },
    { ".cursorignore", "cursor-ignore" },
    { ".cursorindexingignore", "cursor-ignore" },
    { ".cursorrules", "cursor" },
    { ".devcontainer.json", "devcontainer" },
    { ".ds_store", "macos" },
    { ".editorconfig", "editorconfig" },
    { ".eleventy.js", "eleventy" },
    { ".eleventyignore", "eleventy" },
    { ".ember-cli", "ember" },
    { ".ember-cli.js", "ember" },
    { ".env.alpha", "env" },
    { ".env.cat", "env" },
    { ".env.defaults", "env" },
    { ".env.dev", "env" },
    { ".env.dev.local", "env" },
    { ".env.development", "env" },
    { ".env.development.local", "env" },
    { ".env.dist", "env" },
    { ".env.e2e", "env" },
    { ".env.example", "env" },
    { ".env.local", "env" },
    { ".env.preview", "env" },
    { ".env.prod", "env" },
    { ".env.prod.local", "env" },
    { ".env.production", "env" },
    { ".env.production.local", "env" },
    { ".env.qa", "env" },
    { ".env.qa.local", "env" },
    { ".env.sample", "env" },
    { ".env.schema", "env" },
    { ".env.stage", "env" },
    { ".env.staging", "env" },
    { ".env.staging.local", "env" },
    { ".env.template", "env" },
    { ".env.test", "env" },
    { ".env.test.local", "env" },
    { ".env.testing", "env" },
    { ".env.uat", "env" },
    { ".envrc", "envrc" },
    { ".esformatter", "json" },
    { ".eslintcache,", "eslint-ignore" },
    { ".eslintignore", "eslint-ignore" },
    { ".eslintrc", "eslint" },
    { ".eslintrc-jsdoc.js", "eslint" },
    { ".eslintrc-md.js", "eslint" },
    { ".eslintrc.cjs", "eslint" },
    { ".eslintrc.js", "eslint" },
    { ".eslintrc.json", "eslint" },
    { ".eslintrc.yaml", "eslint" },
    { ".eslintrc.yml", "eslint" },
    { ".esmrc", "package-json" },
    { ".firebaserc", "firebase" },
    { ".flutter-plugins", "flutter" },
    { ".flutter-plugins-dependencies", "flutter" },
    { ".fvmrc", "fvm" },
    { ".gdignore", "godot-assets" },
    { ".git", "git" },
    { ".git-blame-ignore", "git" },
    { ".git-blame-ignore-revs", "git" },
    { ".git-for-windows-updater", "git" },
    { ".gitattributes", "git" },
    { ".gitattributes-global", "git" },
    { ".gitattributes_global", "git" },
    { ".gitconfig", "git" },
    { ".gitignore", "git" },
    { ".gitignore-global", "git" },
    { ".gitignore_global", "git" },
    { ".gitinclude", "git" },
    { ".gitkeep", "git" },
    { ".gitmessage", "git" },
    { ".gitmodules", "git" },
    { ".gitpod.yml", "gitpod" },
    { ".gitpreserve", "git" },
    { ".goreleaser.yaml", "release" },
    { ".graphqlconfig", "graphql" },
    { ".graphqlrc", "graphql" },
    { ".graphqlrc.cjs", "graphql" },
    { ".graphqlrc.js", "graphql" },
    { ".graphqlrc.json", "graphql" },
    { ".graphqlrc.toml", "graphql" },
    { ".graphqlrc.ts", "graphql" },
    { ".graphqlrc.yaml", "graphql" },
    { ".graphqlrc.yml", "graphql" },
    { ".helmignore", "helm" },
    { ".histoire.js", "histoire" },
    { ".histoire.ts", "histoire" },
    { ".htaccess", "xml" },
    { ".htpasswd", "key" },
    { ".huskyrc", "husky" },
    { ".huskyrc.js", "husky" },
    { ".huskyrc.json", "husky" },
    { ".huskyrc.yaml", "husky" },
    { ".huskyrc.yml", "husky" },
    { ".io-config.json", "ionic" },
    { ".jestrc", "jest" },
    { ".jestrc.js", "jest" },
    { ".jestrc.json", "jest" },
    { ".jsbeautifyrc", "json" },
    { ".jscsrc", "json" },
    { ".jshintrc", "json" },
    { ".justfile", "just" },
    { ".keep", "git" },
    { ".knip.jsonc", "knip" },
    { ".lintstagedrc", "lint-staged" },
    { ".lintstagedrc.cjs", "lint-staged" },
    { ".lintstagedrc.cts", "lint-staged" },
    { ".lintstagedrc.js", "lint-staged" },
    { ".lintstagedrc.json", "lint-staged" },
    { ".lintstagedrc.mjs", "lint-staged" },
    { ".lintstagedrc.mts", "lint-staged" },
    { ".lintstagedrc.ts", "lint-staged" },
    { ".lintstagedrc.yaml", "lint-staged" },
    { ".lintstagedrc.yml", "lint-staged" },
    { ".liquidrc", "liquid" },
    { ".liquidrc.json", "liquid" },
    { ".luacheckrc", "lua" },
    { ".luaurc", "luau-config" },
    { ".mantle-state.yml", "mantle" },
    { ".metadata", "flutter" },
    { ".mjmlconfig", "mjml" },
    { ".modernizrrc", "modernizr" },
    { ".modernizrrc.js", "modernizr" },
    { ".modernizrrc.json", "modernizr" },
    { ".nest-cli.json", "nest" },
    { ".nestconfig.json", "nest" },
    { ".node-version", "package-json" },
    { ".nowignore", "vercel-ignore" },
    { ".npmignore", "npm-ignore" },
    { ".npmrc", "npm" },
    { ".nuspec", "nuget" },
    { ".nuxtignore", "nuxt-ignore" },
    { ".nuxtrc", "nuxt" },
    { ".nvmrc", "package-json" },
    { ".nxignore", "nx-ignore" },
    { ".phrase.yaml", "phrase" },
    { ".phrase.yml", "phrase" },
    { ".phraseapp.yaml", "phrase" },
    { ".phraseapp.yml", "phrase" },
    { ".pnpmfile.cjs", "pnpm" },
    { ".postcssrc", "postcss" },
    { ".postcssrc.cjs", "postcss" },
    { ".postcssrc.cts", "postcss" },
    { ".postcssrc.js", "postcss" },
    { ".postcssrc.json", "postcss" },
    { ".postcssrc.ts", "postcss" },
    { ".postcssrc.yaml", "postcss" },
    { ".postcssrc.yml", "postcss" },
    { ".pre-commit-config.yaml", "pre-commit" },
    { ".pre-commit-hooks.yaml", "pre-commit" },
    { ".prettierignore", "prettier-ignore" },
    { ".prettierrc", "prettier" },
    { ".prettierrc.cjs", "prettier" },
    { ".prettierrc.cts", "prettier" },
    { ".prettierrc.js", "prettier" },
    { ".prettierrc.json", "prettier" },
    { ".prettierrc.json5", "prettier" },
    { ".prettierrc.mjs", "prettier" },
    { ".prettierrc.mts", "prettier" },
    { ".prettierrc.toml", "prettier" },
    { ".prettierrc.ts", "prettier" },
    { ".prettierrc.yaml", "prettier" },
    { ".prettierrc.yml", "prettier" },
    { ".prototools", "prototools" },
    { ".pug-lintrc", "pug" },
    { ".pug-lintrc.js", "pug" },
    { ".pug-lintrc.json", "pug" },
    { ".puppeteerrc", "puppeteer" },
    { ".puppeteerrc.cjs,", "puppeteer" },
    { ".puppeteerrc.js,", "puppeteer" },
    { ".puppeteerrc.json,", "puppeteer" },
    { ".puppeteerrc.yaml,", "puppeteer" },
    { ".python-version", "python-config" },
    { ".release-please-manifest.json", "gcp" },
    { ".releaserc", "semantic-release" },
    { ".releaserc.cjs", "semantic-release" },
    { ".releaserc.js", "semantic-release" },
    { ".releaserc.json", "semantic-release" },
    { ".releaserc.yaml", "semantic-release" },
    { ".releaserc.yml", "semantic-release" },
    { ".renovaterc", "renovate" },
    { ".renovaterc.json", "renovate" },
    { ".rhistory", "r" },
    { ".rock", "lua-rocks" },
    { ".rockspec", "lua-rocks" },
    { ".ruby-version", "ruby" },
    { ".ruff.toml", "ruff" },
    { ".rustfmt.toml", "rust-config" },
    { ".semgrepignore", "semgrep-ignore" },
    { ".sentryclirc", "sentry" },
    { ".sonarcloud.properties", "sonar-cloud" },
    { ".stackblitzrc", "stackblitz" },
    { ".stylelintcache", "stylelint-ignore" },
    { ".stylelintignore", "stylelint-ignore" },
    { ".stylelintrc", "stylelint" },
    { ".stylelintrc.cjs", "stylelint" },
    { ".stylelintrc.cts", "stylelint" },
    { ".stylelintrc.js", "stylelint" },
    { ".stylelintrc.json", "stylelint" },
    { ".stylelintrc.mjs", "stylelint" },
    { ".stylelintrc.mts", "stylelint" },
    { ".stylelintrc.ts", "stylelint" },
    { ".stylelintrc.yaml", "stylelint" },
    { ".stylelintrc.yml", "stylelint" },
    { ".styluaignore", "stylua-ignore" },
    { ".swiftformat", "swiftformat" },
    { ".taskrc.yaml", "taskfile" },
    { ".taskrc.yml", "taskfile" },
    { ".taurignore", "tauri-ignore" },
    { ".vercelignore", "vercel-ignore" },
    { ".vscodeignore", "vscode-ignore" },
    { ".vuerc", "vue-config" },
    { ".whitesource", "json" },
    { ".yarn-integrity", "yarn" },
    { ".yarnclean", "yarn" },
    { ".yarnrc", "yarn" },
    { ".yarnrc.yaml", "yarn" },
    { ".yarnrc.yml", "yarn" },
    { "7z", "zip" },
    { "CNAME", "http" },
    { "Dockerfile", "docker" },
    { "RData", "rdata" },
    { "Rhistory", "r" },
    { "Rmd", "rmd" },
    { "Rproj", "rproj" },
    { "Tauri.toml", "tauri" },
    { "_sc_", "godot-assets" },
    { "a51", "assembly" },
    { "aac", "audio" },
    { "ab", "amber" },
    { "accdb", "database" },
    { "ace", "adonis" },
    { "ado", "stata" },
    { "adoc", "asciidoc" },
    { "aea", "assembly" },
    { "aep", "adobe-ae" },
    { "afphoto", "image" },
    { "aftman.toml", "foreman" },
    { "agc", "assembly" },
    { "ags", "assembly" },
    { "ahk", "autohotkey" },
    { "ai", "adobe-ai" },
    { "aiff", "audio" },
    { "alac", "audio" },
    { "amber", "amber" },
    { "ami", "image" },
    { "androidmanifest.xml", "android" },
    { "angular-cli.json", "angular" },
    { "angular.json", "angular" },
    { "ansible-lint.yaml", "ansible-lint" },
    { "ansible-lint.yml", "ansible-lint" },
    { "apib", "api-blueprint" },
    { "apiblueprint", "api-blueprint" },
    { "apk", "android" },
    { "apollo.config.js", "apollo" },
    { "apollo.config.ts", "apollo" },
    { "appfile", "fastlane" },
    { "apple-app-site-association", "apple" },
    { "apple-developer-merchantid-domain-association", "apple" },
    { "applypatch-msg", "bash" },
    { "apx", "image" },
    { "argus", "assembly" },
    { "arj", "zip" },
    { "artisan", "laravel" },
    { "asc", "key" },
    { "asciidoc", "asciidoc" },
    { "ase", "image" },
    { "aseprite", "image" },
    { "aseprite-extension", "zip" },
    { "asm", "assembly" },
    { "asp", "html" },
    { "astro", "astro" },
    { "astro.config.cjs", "astro-config" },
    { "astro.config.cts", "astro-config" },
    { "astro.config.js", "astro-config" },
    { "astro.config.mjs", "astro-config" },
    { "astro.config.mts", "astro-config" },
    { "astro.config.ts", "astro-config" },
    { "avi", "video" },
    { "avif", "image" },
    { "awk", "bash" },
    { "axaml", "xaml" },
    { "azure-pipelines-main.yaml", "azure-pipelines" },
    { "azure-pipelines-main.yml", "azure-pipelines" },
    { "azure-pipelines.yaml", "azure-pipelines" },
    { "azure-pipelines.yml", "azure-pipelines" },
    { "babel-plugin-macros.config.js", "babel" },
    { "babel-transform.js", "babel" },
    { "babel.config.cjs", "babel" },
    { "babel.config.js", "babel" },
    { "babel.config.json", "babel" },
    { "babel.config.mjs", "babel" },
    { "bash", "bash" },
    { "bat", "batch" },
    { "bazel", "bazel" },
    { "benchmark.md", "benchmark" },
    { "benchmark.rst", "benchmark" },
    { "benchmark.txt", "benchmark" },
    { "benchmarks.md", "benchmark" },
    { "benchmarks.rst", "benchmark" },
    { "benchmarks.txt", "benchmark" },
    { "bib", "lib" },
    { "bicep", "bicep" },
    { "bicepconfig.json", "bicep" },
    { "bicepparam", "bicep" },
    { "bin", "binary" },
    { "binsource", "assembly" },
    { "biome.json", "biome" },
    { "biome.jsonc", "biome" },
    { "bitbucket-pipelines.yaml", "bitbucket" },
    { "bitbucket-pipelines.yml", "bitbucket" },
    { "blade.php", "laravel" },
    { "blink", "blink" },
    { "blitz.config.js", "blitz" },
    { "blitz.config.ts", "blitz" },
    { "bmap", "font" },
    { "bmp", "image" },
    { "book.toml", "mdbook" },
    { "bower.json", "bower" },
    { "bpg", "image" },
    { "brk", "image" },
    { "browserslist", "browserslist" },
    { "bun.lock", "bun-lock" },
    { "bun.lockb", "bun-lock" },
    { "bunfig.toml", "bun" },
    { "bz", "zip" },
    { "bz2", "zip" },
    { "bzl", "bazel" },
    { "c", "c" },
    { "c++", "cpp" },
    { "cabal", "cabal" },
    { "cabal.project", "cabal" },
    { "caddyfile", "caddy" },
    { "capacitor.config.json", "capacitor" },
    { "capacitor.config.ts", "capacitor" },
    { "cargo.lock", "cargo-lock" },
    { "cargo.toml", "cargo" },
    { "cbl", "cobol" },
    { "cc", "cpp" },
    { "cdp.pid", "json" },
    { "cer", "certificate" },
    { "cert", "certificate" },
    { "cfg", "properties" },
    { "changelog", "changelog" },
    { "changelog.md", "changelog" },
    { "changelog.rst", "changelog" },
    { "changelog.txt", "changelog" },
    { "changes", "changelog" },
    { "changes.md", "changelog" },
    { "changes.rst", "changelog" },
    { "changes.txt", "changelog" },
    { "chart.lock", "helm" },
    { "circle.yml", "circle-ci" },
    { "cjs", "javascript" },
    { "cjs.map", "javascript-map" },
    { "cl", "lisp" },
    { "class", "java-class" },
    { "client.lua", "lua-client" },
    { "client.luau", "luau-client" },
    { "cliff.toml", "git-cliff" },
    { "clip", "image" },
    { "clippy.toml", "rust-config" },
    { "clj", "clojure" },
    { "cljc", "clojure" },
    { "cljs", "clojure" },
    { "cls", "salesforce" },
    { "cmake", "cmake" },
    { "cmakecache.txt", "cmake" },
    { "cmakelists.txt", "cmake" },
    { "cmd", "batch" },
    { "cmx", "ocaml" },
    { "cob", "cobol" },
    { "code-profile", "vscode" },
    { "code-search", "search" },
    { "code-snippets", "vscode" },
    { "code-workplace", "vscode" },
    { "code-workspace", "vscode" },
    { "code_of_conduct", "code-of-conduct" },
    { "code_of_conduct.md", "code-of-conduct" },
    { "code_of_conduct.txt", "code-of-conduct" },
    { "codeowners", "codeowners" },
    { "coffee", "coffeescript" },
    { "commit-msg", "bash" },
    { "commitlint.config.cjs", "commitlint" },
    { "commitlint.config.cts", "commitlint" },
    { "commitlint.config.js", "commitlint" },
    { "commitlint.config.ts", "commitlint" },
    { "comp", "shader" },
    { "comp.glsl", "shader" },
    { "comp.hlsl", "shader" },
    { "compose.alpha.yaml", "docker-compose" },
    { "compose.alpha.yml", "docker-compose" },
    { "compose.beta.yaml", "docker-compose" },
    { "compose.beta.yml", "docker-compose" },
    { "compose.ci.yaml", "docker-compose" },
    { "compose.ci.yml", "docker-compose" },
    { "compose.dev.yaml", "docker-compose" },
    { "compose.dev.yml", "docker-compose" },
    { "compose.development.yaml", "docker-compose" },
    { "compose.development.yml", "docker-compose" },
    { "compose.local.yaml", "docker-compose" },
    { "compose.local.yml", "docker-compose" },
    { "compose.override.yaml", "docker-compose" },
    { "compose.override.yml", "docker-compose" },
    { "compose.prod.yaml", "docker-compose" },
    { "compose.prod.yml", "docker-compose" },
    { "compose.production.yaml", "docker-compose" },
    { "compose.production.yml", "docker-compose" },
    { "compose.stage.yaml", "docker-compose" },
    { "compose.stage.yml", "docker-compose" },
    { "compose.staging.yaml", "docker-compose" },
    { "compose.staging.yml", "docker-compose" },
    { "compose.test.yaml", "docker-compose" },
    { "compose.test.yml", "docker-compose" },
    { "compose.testing.yaml", "docker-compose" },
    { "compose.testing.yml", "docker-compose" },
    { "compose.web.yaml", "docker-compose" },
    { "compose.web.yml", "docker-compose" },
    { "compose.worker.yaml", "docker-compose" },
    { "compose.worker.yml", "docker-compose" },
    { "compose.yaml", "docker-compose" },
    { "compose.yml", "docker-compose" },
    { "composer.lock", "json" },
    { "compute.glsl", "shader" },
    { "compute.hlsl", "shader" },
    { "computeshader", "shader" },
    { "conf", "properties" },
    { "config", "properties" },
    { "config.dart", "dart-generated" },
    { "containerfile", "docker" },
    { "containerfile.alpha", "docker" },
    { "containerfile.beta", "docker" },
    { "containerfile.ci", "docker" },
    { "containerfile.dev", "docker" },
    { "containerfile.development", "docker" },
    { "containerfile.local", "docker" },
    { "containerfile.prod", "docker" },
    { "containerfile.production", "docker" },
    { "containerfile.stage", "docker" },
    { "containerfile.staging", "docker" },
    { "containerfile.test", "docker" },
    { "containerfile.testing", "docker" },
    { "containerfile.web", "docker" },
    { "containerfile.worker", "docker" },
    { "containerignore", "docker-ignore" },
    { "contributing", "contributing" },
    { "contributing.md", "contributing" },
    { "contributing.rst", "contributing" },
    { "contributing.txt", "contributing" },
    { "copying", "license" },
    { "copying.md", "license" },
    { "copying.rst", "license" },
    { "copying.txt", "license" },
    { "copyright", "license" },
    { "copyright.md", "license" },
    { "copyright.rst", "license" },
    { "copyright.txt", "license" },
    { "cp", "cpp" },
    { "cpp", "cpp" },
    { "cpt", "image" },
    { "cr", "crystal" },
    { "crt", "certificate" },
    { "cs", "csharp" },
    { "csh", "bash" },
    { "csharp", "csharp" },
    { "cshtml", "razor" },
    { "cson", "coffeescript" },
    { "cspell.config.cjs", "cspell" },
    { "cspell.config.js", "cspell" },
    { "cspell.config.yaml", "cspell" },
    { "cspell.config.yml", "cspell" },
    { "cspell.json", "cspell" },
    { "cspell.yaml", "cspell" },
    { "cspell.yml", "cspell" },
    { "csproj", "visual-studio" },
    { "csproj.user", "visual-studio" },
    { "css", "css" },
    { "css.map", "css-map" },
    { "css.ts", "vanilla-extract" },
    { "csv", "csv" },
    { "csx", "csharp" },
    { "cts", "typescript" },
    { "cu", "cuda" },
    { "cue", "cue" },
    { "cuh", "cuda" },
    { "cur", "image" },
    { "cxx", "cpp" },
    { "cy.js", "javascript-test" },
    { "cy.jsx", "javascript-test" },
    { "cy.ts", "typescript-test" },
    { "cy.tsx", "typescript-test" },
    { "cypress.config.cjs", "cypress" },
    { "cypress.config.js", "cypress" },
    { "cypress.config.mjs", "cypress" },
    { "cypress.config.ts", "cypress" },
    { "cypress.env.json", "cypress" },
    { "cypress.json", "cypress" },
    { "d", "d" },
    { "d.cts", "typescript-def" },
    { "d.mts", "typescript-def" },
    { "d.ts", "typescript-def" },
    { "darklua.json", "darklua" },
    { "darklua.json5", "darklua" },
    { "dart", "dart" },
    { "dat", "database" },
    { "db", "zip" },
    { "db3", "database" },
    { "dds", "image" },
    { "deliverfile", "fastlane" },
    { "deno.json", "deno" },
    { "deno.jsonc", "deno" },
    { "deno.lock", "deno_lock" },
    { "dependabot.yaml", "dependabot" },
    { "dependabot.yml", "dependabot" },
    { "devcontainer.json", "devcontainer" },
    { "dex", "android" },
    { "dhall", "dhall" },
    { "dhallb", "dhall" },
    { "di", "d" },
    { "dio", "drawio" },
    { "directory.build.props", "msbuild" },
    { "directory.build.rsp", "msbuild" },
    { "directory.build.targets", "msbuild" },
    { "directory.packages.props", "msbuild" },
    { "djt", "django" },
    { "dlc", "properties" },
    { "dmn", "xml" },
    { "dng", "image" },
    { "do", "stata" },
    { "doc", "ms-word" },
    { "docker-compose.alpha.yaml", "docker-compose" },
    { "docker-compose.alpha.yml", "docker-compose" },
    { "docker-compose.beta.yaml", "docker-compose" },
    { "docker-compose.beta.yml", "docker-compose" },
    { "docker-compose.ci.yaml", "docker-compose" },
    { "docker-compose.ci.yml", "docker-compose" },
    { "docker-compose.dev.yaml", "docker-compose" },
    { "docker-compose.dev.yml", "docker-compose" },
    { "docker-compose.development.yaml", "docker-compose" },
    { "docker-compose.development.yml", "docker-compose" },
    { "docker-compose.local.yaml", "docker-compose" },
    { "docker-compose.local.yml", "docker-compose" },
    { "docker-compose.override.yaml", "docker-compose" },
    { "docker-compose.override.yml", "docker-compose" },
    { "docker-compose.prod.yaml", "docker-compose" },
    { "docker-compose.prod.yml", "docker-compose" },
    { "docker-compose.production.yaml", "docker-compose" },
    { "docker-compose.production.yml", "docker-compose" },
    { "docker-compose.stage.yaml", "docker-compose" },
    { "docker-compose.stage.yml", "docker-compose" },
    { "docker-compose.staging.yaml", "docker-compose" },
    { "docker-compose.staging.yml", "docker-compose" },
    { "docker-compose.test.yaml", "docker-compose" },
    { "docker-compose.test.yml", "docker-compose" },
    { "docker-compose.testing.yaml", "docker-compose" },
    { "docker-compose.testing.yml", "docker-compose" },
    { "docker-compose.web.yaml", "docker-compose" },
    { "docker-compose.web.yml", "docker-compose" },
    { "docker-compose.worker.yaml", "docker-compose" },
    { "docker-compose.worker.yml", "docker-compose" },
    { "docker-compose.yaml", "docker-compose" },
    { "docker-compose.yml", "docker-compose" },
    { "dockerfile", "docker" },
    { "dockerfile.alpha", "docker" },
    { "dockerfile.beta", "docker" },
    { "dockerfile.ci", "docker" },
    { "dockerfile.dev", "docker" },
    { "dockerfile.development", "docker" },
    { "dockerfile.local", "docker" },
    { "dockerfile.prod", "docker" },
    { "dockerfile.production", "docker" },
    { "dockerfile.stage", "docker" },
    { "dockerfile.staging", "docker" },
    { "dockerfile.test", "docker" },
    { "dockerfile.testing", "docker" },
    { "dockerfile.web", "docker" },
    { "dockerfile.worker", "docker" },
    { "dockerignore", "docker-ignore" },
    { "docm", "ms-word" },
    { "docusaurus.config.cjs", "docusaurus" },
    { "docusaurus.config.js", "docusaurus" },
    { "docusaurus.config.mjs", "docusaurus" },
    { "docusaurus.config.ts", "docusaurus" },
    { "docx", "ms-word" },
    { "dot", "ms-word" },
    { "dotm", "ms-word" },
    { "dotx", "ms-word" },
    { "drawio", "drawio" },
    { "drizzle.config.js", "drizzle-orm" },
    { "drizzle.config.ts", "drizzle-orm" },
    { "dta", "stata" },
    { "dtd", "xml" },
    { "dtx", "latex" },
    { "dub.json", "dub" },
    { "dub.sdl", "dub" },
    { "dub.selections.json", "dub-selections" },
    { "e2e-spec.cjs", "javascript-test" },
    { "e2e-spec.cts", "typescript-test" },
    { "e2e-spec.js", "javascript-test" },
    { "e2e-spec.mjs", "javascript-test" },
    { "e2e-spec.mts", "typescript-test" },
    { "e2e-spec.ts", "typescript-test" },
    { "ecr", "crystal" },
    { "eex", "elixir" },
    { "ejs", "ejs" },
    { "eleventy.config.cjs", "eleventy" },
    { "eleventy.config.js", "eleventy" },
    { "eleventy.config.mjs", "eleventy" },
    { "elm", "elm" },
    { "ember-cli-builds.js", "ember" },
    { "entitlements", "certificate" },
    { "env", "env" },
    { "eot", "font" },
    { "epp", "puppet" },
    { "eps", "image" },
    { "erb", "ruby" },
    { "erl", "erlang" },
    { "esbuild.cjs", "esbuild" },
    { "esbuild.config.cjs", "esbuild" },
    { "esbuild.config.js", "esbuild" },
    { "esbuild.config.mjs", "esbuild" },
    { "esbuild.config.ts", "esbuild" },
    { "esbuild.js", "esbuild" },
    { "esbuild.mjs", "esbuild" },
    { "esbuild.ts", "esbuild" },
    { "eslint.config.cjs", "eslint" },
    { "eslint.config.cts", "eslint" },
    { "eslint.config.js", "eslint" },
    { "eslint.config.mjs", "eslint" },
    { "eslint.config.mts", "eslint" },
    { "eslint.config.ts", "eslint" },
    { "esx", "javascript" },
    { "ex", "elixir" },
    { "exe", "exe" },
    { "exr", "image" },
    { "exrc", "vim" },
    { "exs", "elixir" },
    { "f", "fortran" },
    { "f03", "fortran" },
    { "f08", "fortran" },
    { "f77", "fortran" },
    { "f90", "fortran" },
    { "f95", "fortran" },
    { "fast", "lisp" },
    { "fastfile", "fastlane" },
    { "favicon.ico", "favicon" },
    { "fbx", "3d" },
    { "feature", "cucumber" },
    { "features", "cucumber" },
    { "fig", "figma" },
    { "firebase.json", "firebase" },
    { "firestore.indexes.json", "firebase" },
    { "firestore.rules", "firebase" },
    { "fish", "bash" },
    { "flac", "audio" },
    { "flake.lock", "nix-lock" },
    { "flv", "video" },
    { "fnt", "font" },
    { "font", "font" },
    { "fonts", "font" },
    { "for", "fortran" },
    { "foreman.toml", "foreman" },
    { "fpx", "image" },
    { "frag", "shader" },
    { "frag.glsl", "shader" },
    { "fragment.glsl", "shader" },
    { "fragmentshader", "shader" },
    { "freezed.dart", "dart-generated" },
    { "fs", "fsharp" },
    { "fs.glsl", "shader" },
    { "fsi", "fsharp" },
    { "fsproj", "visual-studio" },
    { "fsproj.user", "visual-studio" },
    { "fsx", "fsharp" },
    { "fvm_config.json", "fvm" },
    { "g.dart", "dart-generated" },
    { "g4", "antlr" },
    { "gatsby-browser.js", "gatsby" },
    { "gatsby-browser.tsx", "gatsby" },
    { "gatsby-config.js", "gatsby" },
    { "gatsby-config.mjs", "gatsby" },
    { "gatsby-config.ts", "gatsby" },
    { "gatsby-node.js", "gatsby" },
    { "gatsby-node.mjs", "gatsby" },
    { "gatsby-node.ts", "gatsby" },
    { "gatsby-ssr.js", "gatsby" },
    { "gatsby-ssr.tsx", "gatsby" },
    { "gbr", "image" },
    { "gd", "godot" },
    { "gd.uid", "godot-assets" },
    { "gdextension", "godot-assets" },
    { "gdnlib", "godot-assets" },
    { "gdns", "godot-assets" },
    { "gdshader", "godot-assets" },
    { "gdshaderinc", "godot-assets" },
    { "gemfile", "ruby-gem" },
    { "gemfile.lock", "ruby-gem-lock" },
    { "geom", "shader" },
    { "geom.glsl", "shader" },
    { "geom.hlsl", "shader" },
    { "geometry.glsl", "shader" },
    { "geometry.hlsl", "shader" },
    { "geometryshader", "shader" },
    { "gif", "image" },
    { "gifv", "video" },
    { "git-history", "git" },
    { "gitlab-ci.yaml", "gitlab" },
    { "gitlab-ci.yml", "gitlab" },
    { "glb", "3d" },
    { "gleam", "gleam" },
    { "gleam.toml", "gleam-config" },
    { "glsl", "shader" },
    { "gltf", "3d" },
    { "gnumakefile", "makefile" },
    { "go", "go" },
    { "go.html", "go-template" },
    { "go.mod", "go-mod" },
    { "go.sum", "go-mod" },
    { "go.tmp", "go-template" },
    { "go.work", "go-mod" },
    { "go.work.sum", "go-mod" },
    { "godot", "godot-assets" },
    { "gohtml", "go-template" },
    { "gotmpl", "go-template" },
    { "gpg", "key" },
    { "gql", "graphql" },
    { "gr.dart", "dart-generated" },
    { "gradle", "gradle" },
    { "gradle-wrapper.properties", "gradle" },
    { "gradle.properties", "gradle" },
    { "gradlew", "gradle" },
    { "graphql", "graphql" },
    { "graphql.config.cjs", "graphql" },
    { "graphql.config.js", "graphql" },
    { "graphql.config.json", "graphql" },
    { "graphql.config.toml", "graphql" },
    { "graphql.config.ts", "graphql" },
    { "graphql.config.yaml", "graphql" },
    { "graphql.config.yml", "graphql" },
    { "groovy", "groovy" },
    { "gs.glsl", "shader" },
    { "gulpfile.babel.js", "gulp" },
    { "gulpfile.cts", "gulp" },
    { "gulpfile.js", "gulp" },
    { "gulpfile.mjs", "gulp" },
    { "gulpfile.mts", "gulp" },
    { "gulpfile.ts", "gulp" },
    { "gvimrc", "vim" },
    { "gymfile", "fastlane" },
    { "gz", "zip" },
    { "h", "c-header" },
    { "h++", "cpp-header" },
    { "ha", "hare" },
    { "hacking", "hacking" },
    { "hacking.md", "hacking" },
    { "hacking.txt", "hacking" },
    { "haml", "haml" },
    { "hardhat.config.js", "hardhat" },
    { "hardhat.config.ts", "hardhat" },
    { "hbs", "handlebars" },
    { "heex", "elixir" },
    { "heic", "image" },
    { "heif", "image" },
    { "hh", "cpp-header" },
    { "histoire.config.js", "histoire" },
    { "histoire.config.ts", "histoire" },
    { "hjson", "json" },
    { "hlsl", "shader" },
    { "hp", "cpp-header" },
    { "hpp", "cpp-header" },
    { "hs", "haskell" },
    { "htm", "html" },
    { "html", "html" },
    { "html_vm", "html" },
    { "http", "http" },
    { "huff", "huff" },
    { "hugo.json", "hugo" },
    { "hugo.toml", "hugo" },
    { "hugo.yaml", "hugo" },
    { "humans.txt", "humans" },
    { "husky.config.js", "husky" },
    { "hx", "haxe" },
    { "hxx", "cpp-header" },
    { "i", "c" },
    { "iced", "coffeescript" },
    { "icns", "image" },
    { "ico", "image" },
    { "ii", "cpp" },
    { "img", "image" },
    { "iml", "xml" },
    { "inc", "assembly" },
    { "indb", "adobe-id" },
    { "indd", "adobe-id" },
    { "indl", "adobe-id" },
    { "ini", "properties" },
    { "inky.php", "laravel" },
    { "inl", "cpp-header" },
    { "ino", "arduino" },
    { "ionic.config.json", "ionic" },
    { "ipynb", "jupyter" },
    { "j2", "jinja" },
    { "jade", "pug" },
    { "jar", "java-jar" },
    { "java", "java" },
    { "jb2", "image" },
    { "jbig2", "image" },
    { "jest-e2e.config.cjs", "jest" },
    { "jest-e2e.config.cts", "jest" },
    { "jest-e2e.config.js", "jest" },
    { "jest-e2e.config.json", "jest" },
    { "jest-e2e.config.mjs", "jest" },
    { "jest-e2e.config.mts", "jest" },
    { "jest-e2e.config.ts", "jest" },
    { "jest-e2e.json", "jest" },
    { "jest-github-actions-reporter.js", "jest" },
    { "jest-preset.cjs", "jest" },
    { "jest-preset.js", "jest" },
    { "jest-preset.json", "jest" },
    { "jest-preset.mjs", "jest" },
    { "jest-unit.config.js", "jest" },
    { "jest.config.cjs", "jest" },
    { "jest.config.cts", "jest" },
    { "jest.config.js", "jest" },
    { "jest.config.json", "jest" },
    { "jest.config.mjs", "jest" },
    { "jest.config.mts", "jest" },
    { "jest.config.ts", "jest" },
    { "jest.e2e.config.cjs", "jest" },
    { "jest.e2e.config.cts", "jest" },
    { "jest.e2e.config.js", "jest" },
    { "jest.e2e.config.json", "jest" },
    { "jest.e2e.config.mjs", "jest" },
    { "jest.e2e.config.mts", "jest" },
    { "jest.e2e.config.ts", "jest" },
    { "jest.e2e.json", "jest" },
    { "jest.json", "jest" },
    { "jest.preset.cjs", "jest" },
    { "jest.preset.js", "jest" },
    { "jest.preset.json", "jest" },
    { "jest.preset.mjs", "jest" },
    { "jest.setup.js", "jest" },
    { "jest.setup.ts", "jest" },
    { "jest.teardown.js", "jest" },
    { "jfif", "image" },
    { "jinja", "jinja" },
    { "jinja-html", "jinja" },
    { "jinja2", "jinja" },
    { "jl", "julia" },
    { "jng", "image" },
    { "jpeg", "image" },
    { "jpg", "image" },
    { "jrxml", "xml" },
    { "js", "javascript" },
    { "js.map", "javascript-map" },
    { "js.snap", "javascript-test" },
    { "jsconfig.json", "javascript-config" },
    { "json", "json" },
    { "json5", "json" },
    { "jsonc", "json" },
    { "jsonl", "json" },
    { "jsp", "java" },
    { "jsx", "javascript-react" },
    { "jsx.snap", "javascript-test" },
    { "jucer", "juce" },
    { "jule", "jule" },
    { "jule.mod", "jule" },
    { "just", "just" },
    { "justfile", "just" },
    { "jvm.config", "apache" },
    { "jxr", "image" },
    { "kbuild", "makefile" },
    { "kdl", "kdl" },
    { "key", "key" },
    { "keystore", "key" },
    { "knip.config.js", "knip" },
    { "knip.config.ts", "knip" },
    { "knip.js", "knip" },
    { "knip.json", "knip" },
    { "knip.jsonc", "knip" },
    { "knip.ts", "knip" },
    { "kra", "image" },
    { "ksh", "bash" },
    { "kt", "kotlin" },
    { "kts", "kotlin" },
    { "latte", "latte" },
    { "leex", "elixir" },
    { "lerna.json", "lerna" },
    { "less", "less" },
    { "lib", "lib" },
    { "licence", "license" },
    { "licence-agpl", "license" },
    { "licence-apache", "license" },
    { "licence-bsd", "license" },
    { "licence-gpl", "license" },
    { "licence-lgpl", "license" },
    { "licence-mit", "license" },
    { "licence.md", "license" },
    { "licence.rst", "license" },
    { "licence.txt", "license" },
    { "license", "license" },
    { "license-agpl", "license" },
    { "license-apache", "license" },
    { "license-bsd", "license" },
    { "license-gpl", "license" },
    { "license-lgpl", "license" },
    { "license-mit", "license" },
    { "license.md", "license" },
    { "license.rst", "license" },
    { "license.txt", "license" },
    { "lint-staged.config.cjs", "lint-staged" },
    { "lint-staged.config.cts", "lint-staged" },
    { "lint-staged.config.js", "lint-staged" },
    { "lint-staged.config.mjs", "lint-staged" },
    { "lint-staged.config.mts", "lint-staged" },
    { "lint-staged.config.ts", "lint-staged" },
    { "liquid", "liquid" },
    { "lisp", "lisp" },
    { "log", "log" },
    { "lsp", "lisp" },
    { "ltx", "latex" },
    { "lua", "lua" },
    { "luau", "luau" },
    { "m", "matlab" },
    { "m2v", "video" },
    { "m4a", "audio" },
    { "m4p", "audio" },
    { "m4v", "video" },
    { "ma", "3d" },
    { "makefile", "makefile" },
    { "manifest", "xml" },
    { "mantle.yml", "mantle" },
    { "markdown", "markdown" },
    { "marko", "marko" },
    { "mat", "matlab" },
    { "matchfile", "fastlane" },
    { "maven.config", "apache" },
    { "mb", "3d" },
    { "md", "markdown" },
    { "mdb", "database" },
    { "mdp", "image" },
    { "mdx", "markdown-mdx" },
    { "mermaid", "mermaid" },
    { "meson.build", "meson" },
    { "meson_options.txt", "meson" },
    { "mi", "c" },
    { "mid", "midi" },
    { "midi", "midi" },
    { "mii", "cpp" },
    { "mitigus", "assembly" },
    { "mjml", "mjml" },
    { "mjs", "javascript" },
    { "mjs.map", "javascript-map" },
    { "mk", "makefile" },
    { "mkv", "video" },
    { "ml", "ocaml" },
    { "mli", "ocaml" },
    { "mmd", "mermaid" },
    { "mogg", "audio" },
    { "moon.yaml", "moonrepo" },
    { "moon.yml", "moonrepo" },
    { "moonwave.toml", "moonwave" },
    { "mov", "video" },
    { "mp2", "video" },
    { "mp3", "audio" },
    { "mp4", "video" },
    { "mpe", "video" },
    { "mpeg", "video" },
    { "mpg", "video" },
    { "mpv", "video" },
    { "mrf", "font" },
    { "ms", "assembly" },
    { "msi", "exe" },
    { "mts", "typescript" },
    { "mustache", "handlebars" },
    { "nasm", "assembly" },
    { "nativescript.config.js", "nativescript" },
    { "nativescript.config.ts", "nativescript" },
    { "ndjson", "json" },
    { "nest-cli.json", "nest" },
    { "nestconfig.json", "nest" },
    { "netlify.json", "netlify" },
    { "netlify.toml", "netlify" },
    { "netlify.yaml", "netlify" },
    { "netlify.yml", "netlify" },
    { "next.config.js", "next" },
    { "next.config.mjs", "next" },
    { "next.config.mts", "next" },
    { "next.config.ts", "next" },
    { "nf", "nextflow" },
    { "ng-package.json", "angular" },
    { "ng-template", "angular" },
    { "nginx", "nginx" },
    { "nginx.conf", "nginx" },
    { "nginxconf", "nginx" },
    { "nginxconfig", "nginx" },
    { "nim", "nim" },
    { "nimble", "nim" },
    { "ninja", "ninja" },
    { "nix", "nix" },
    { "njk", "nunjucks" },
    { "nodemon-debug.json", "nodemon" },
    { "nodemon.json", "nodemon" },
    { "now.json", "vercel" },
    { "nqp", "perl" },
    { "ntf", "font" },
    { "nuget.config", "nuget" },
    { "nuget.exe", "nuget" },
    { "nunjucks", "nunjucks" },
    { "nupkg", "nuget" },
    { "nut", "squirrel" },
    { "nuxt.config.js", "nuxt" },
    { "nuxt.config.ts", "nuxt" },
    { "nx.json", "nx" },
    { "obj", "3d" },
    { "odin", "odin" },
    { "odp", "ms-powerpoint" },
    { "ods", "ms-excel" },
    { "odt", "ms-word" },
    { "odttf", "font" },
    { "oga", "audio" },
    { "ogg", "video" },
    { "ogv", "video" },
    { "option", "properties" },
    { "opus", "audio" },
    { "ora", "image" },
    { "org", "org" },
    { "otf", "font" },
    { "owners", "codeowners" },
    { "p", "prolog" },
    { "p6", "perl" },
    { "package-lock.json", "npm-lock" },
    { "package.json", "package-json" },
    { "panda.config.cjs", "panda-css" },
    { "panda.config.js", "panda-css" },
    { "panda.config.mjs", "panda-css" },
    { "panda.config.mts", "panda-css" },
    { "panda.config.ts", "panda-css" },
    { "paq8n", "zip" },
    { "paq8o", "zip" },
    { "passwd", "key" },
    { "patch", "git" },
    { "pbm", "image" },
    { "pcss", "postcss" },
    { "pdb", "database" },
    { "pdf", "pdf" },
    { "pdn", "image" },
    { "pem", "key" },
    { "pesde.lock", "pesde-lock" },
    { "pesde.toml", "pesde" },
    { "pfx", "certificate" },
    { "pgf", "image" },
    { "pgm", "image" },
    { "pgsql", "database" },
    { "php", "php" },
    { "phtml", "phtml" },
    { "pic", "image" },
    { "pixel.hlsl", "shader" },
    { "pixi.lock", "pixi-lock" },
    { "pixi.toml", "pixi" },
    { "pkb", "database" },
    { "pkg", "zip" },
    { "pks", "database" },
    { "pl", "perl" },
    { "pl6", "perl" },
    { "plantuml", "plantuml" },
    { "playwright-ct.config.js", "playwright" },
    { "playwright-ct.config.mjs", "playwright" },
    { "playwright-ct.config.ts", "playwright" },
    { "playwright.config.base.js", "playwright" },
    { "playwright.config.base.mjs", "playwright" },
    { "playwright.config.base.ts", "playwright" },
    { "playwright.config.js", "playwright" },
    { "playwright.config.mjs", "playwright" },
    { "playwright.config.ts", "playwright" },
    { "plist", "xml" },
    { "plopfile.cjs", "plop" },
    { "plopfile.js", "plop" },
    { "plopfile.mjs", "plop" },
    { "plopfile.ts", "plop" },
    { "plpgsql", "database" },
    { "pm", "perl" },
    { "pm6", "perl" },
    { "png", "image" },
    { "pnm", "image" },
    { "pnpm-lock.yaml", "pnpm-lock" },
    { "pnpm-workspace.yaml", "pnpm" },
    { "pod", "perl" },
    { "poetry.lock", "poetry-lock" },
    { "pom.xml", "apache" },
    { "post-applypatch", "bash" },
    { "post-checkout", "bash" },
    { "post-commit", "bash" },
    { "post-merge", "bash" },
    { "post-receive", "bash" },
    { "post-rewrite", "bash" },
    { "post-update", "bash" },
    { "postcss.config.cjs", "postcss" },
    { "postcss.config.cts", "postcss" },
    { "postcss.config.js", "postcss" },
    { "postcss.config.mjs", "postcss" },
    { "postcss.config.mts", "postcss" },
    { "postcss.config.ts", "postcss" },
    { "postgres", "database" },
    { "potm", "ms-powerpoint" },
    { "potx", "ms-powerpoint" },
    { "pp", "puppet" },
    { "ppa", "ms-powerpoint" },
    { "ppam", "ms-powerpoint" },
    { "ppm", "image" },
    { "pps", "ms-powerpoint" },
    { "ppsm", "ms-powerpoint" },
    { "ppsx", "ms-powerpoint" },
    { "ppt", "ms-powerpoint" },
    { "pptm", "ms-powerpoint" },
    { "pptx", "ms-powerpoint" },
    { "prc", "3d" },
    { "pre-applypatch", "bash" },
    { "pre-auto-gc", "bash" },
    { "pre-commit", "bash" },
    { "pre-push", "bash" },
    { "pre-rebase", "bash" },
    { "pre-receive", "bash" },
    { "prefs", "properties" },
    { "premake.lua", "premake" },
    { "premake4.lua", "premake" },
    { "premake5.lua", "premake" },
    { "prepare-commit-message", "bash" },
    { "prettier.config.cjs", "prettier" },
    { "prettier.config.cts", "prettier" },
    { "prettier.config.js", "prettier" },
    { "prettier.config.mjs", "prettier" },
    { "prettier.config.mts", "prettier" },
    { "prettier.config.ts", "prettier" },
    { "prisma", "prisma" },
    { "prisma.config.cjs", "prisma" },
    { "prisma.config.cts", "prisma" },
    { "prisma.config.js", "prisma" },
    { "prisma.config.mjs", "prisma" },
    { "prisma.config.mts", "prisma" },
    { "prisma.config.ts", "prisma" },
    { "prisma.yml", "prisma" },
    { "pro", "prolog" },
    { "procfile", "heroku" },
    { "project", "xml" },
    { "prop", "properties" },
    { "properties", "properties" },
    { "props", "properties" },
    { "proto", "proto" },
    { "ps1", "powershell" },
    { "ps1xml", "powershell" },
    { "psb", "image" },
    { "psc1", "powershell" },
    { "psd", "adobe-ps" },
    { "psd1", "powershell" },
    { "psgi", "perl" },
    { "psm1", "powershell" },
    { "psql", "database" },
    { "pssc", "powershell" },
    { "psv", "csv" },
    { "pu", "plantuml" },
    { "pub", "key" },
    { "pug", "pug" },
    { "puml", "plantuml" },
    { "puppeteer.config.cjs", "puppeteer" },
    { "puppeteer.config.js", "puppeteer" },
    { "px.hlsl", "shader" },
    { "py", "python" },
    { "pyc", "python-compiled" },
    { "pyd", "python-compiled" },
    { "pyo", "python-compiled" },
    { "pyproject.toml", "python-config" },
    { "qt", "video" },
    { "r", "r" },
    { "raku", "perl" },
    { "rakudoc", "perl" },
    { "rakumod", "perl" },
    { "rakutest", "perl" },
    { "rar", "zip" },
    { "raw", "image" },
    { "rb", "ruby" },
    { "rbs", "ruby" },
    { "rbxl", "roblox" },
    { "rbxlx", "roblox" },
    { "rbxm", "roblox" },
    { "rbxmx", "roblox" },
    { "rdata", "rdata" },
    { "re", "reason" },
    { "readme", "readme" },
    { "readme.md", "readme" },
    { "readme.rst", "readme" },
    { "readme.txt", "readme" },
    { "reb", "image" },
    { "redwood.toml", "redwood" },
    { "rei", "reason" },
    { "release-please-config.json", "gcp" },
    { "release.config.cjs", "semantic-release" },
    { "release.config.js", "semantic-release" },
    { "remix.config.js", "remix" },
    { "remix.config.ts", "remix" },
    { "renovate-config.json", "renovate" },
    { "renovate.json", "renovate" },
    { "renovate.json5", "renovate" },
    { "requirements-dev.txt", "python-config" },
    { "requirements-test.txt", "python-config" },
    { "requirements.txt", "python-config" },
    { "res", "rescript" },
    { "rest", "http" },
    { "resx", "xml" },
    { "rkt", "racket" },
    { "rm", "video" },
    { "rmd", "rmd" },
    { "rmvb", "video" },
    { "robots.txt", "robots" },
    { "rocket.toml", "rocket" },
    { "rokit.toml", "rokit" },
    { "rollup-config.js", "rollup" },
    { "rollup-config.mjs", "rollup" },
    { "rollup-config.ts", "rollup" },
    { "rollup.config.base.js", "rollup" },
    { "rollup.config.base.mjs", "rollup" },
    { "rollup.config.base.ts", "rollup" },
    { "rollup.config.common.js", "rollup" },
    { "rollup.config.common.mjs", "rollup" },
    { "rollup.config.common.ts", "rollup" },
    { "rollup.config.dev.js", "rollup" },
    { "rollup.config.dev.mjs", "rollup" },
    { "rollup.config.dev.ts", "rollup" },
    { "rollup.config.js", "rollup" },
    { "rollup.config.mjs", "rollup" },
    { "rollup.config.prod.js", "rollup" },
    { "rollup.config.prod.mjs", "rollup" },
    { "rollup.config.prod.ts", "rollup" },
    { "rollup.config.prod.vendor.js", "rollup" },
    { "rollup.config.prod.vendor.mjs", "rollup" },
    { "rollup.config.prod.vendor.ts", "rollup" },
    { "rollup.config.ts", "rollup" },
    { "ron", "rust" },
    { "rproj", "rproj" },
    { "rs", "rust" },
    { "rsml", "rsml" },
    { "rst", "markdown" },
    { "rtf", "ms-word" },
    { "ruff.toml", "ruff" },
    { "ruleset", "visual-studio" },
    { "rust-toolchain.toml", "rust-config" },
    { "rustfmt.toml", "rust-config" },
    { "s", "assembly" },
    { "sai", "image" },
    { "sass", "sass" },
    { "sc", "super-collider" },
    { "scala", "scala" },
    { "scanfile", "fastlane" },
    { "scd", "super-collider" },
    { "schema.json", "json-schema" },
    { "scm", "scheme" },
    { "scss", "sass" },
    { "sdf", "slidesk" },
    { "sdt", "slidesk" },
    { "security", "security" },
    { "security.md", "security" },
    { "security.txt", "security" },
    { "selene.toml", "luau-check" },
    { "selene.yaml", "luau-check" },
    { "selene.yml", "luau-check" },
    { "semgrep.yml", "semgrep" },
    { "server.lua", "lua-server" },
    { "server.luau", "luau-server" },
    { "serverless.js", "serverless" },
    { "serverless.json", "serverless" },
    { "serverless.ts", "serverless" },
    { "serverless.yaml", "serverless" },
    { "serverless.yml", "serverless" },
    { "settings", "properties" },
    { "sh", "bash" },
    { "shader", "shader" },
    { "sketch", "sketch" },
    { "sln", "visual-studio" },
    { "sln.dotsettings", "properties" },
    { "sln.dotsettings.user", "properties" },
    { "slnf", "visual-studio" },
    { "slnx", "visual-studio" },
    { "smali", "android" },
    { "snapfile", "fastlane" },
    { "snowpack.config.cjs", "snowpack" },
    { "snowpack.config.cts", "snowpack" },
    { "snowpack.config.js", "snowpack" },
    { "snowpack.config.json", "snowpack" },
    { "snowpack.config.mjs", "snowpack" },
    { "snowpack.config.mts", "snowpack" },
    { "snowpack.config.ts", "snowpack" },
    { "snowpack.deps.json", "snowpack" },
    { "sol", "solidity" },
    { "sonar-project.properties", "sonar-cloud" },
    { "sonarcloud.yaml", "sonar-cloud" },
    { "spec-d.ts", "typescript-test" },
    { "spec.cjs", "javascript-test" },
    { "spec.cts", "typescript-test" },
    { "spec.js", "javascript-test" },
    { "spec.jsx", "javascript-test" },
    { "spec.lua", "lua-test" },
    { "spec.luau", "luau-test" },
    { "spec.mjs", "javascript-test" },
    { "spec.mts", "typescript-test" },
    { "spec.ts", "typescript-test" },
    { "spec.tsx", "typescript-test" },
    { "spwn", "spwn" },
    { "sql", "database" },
    { "sqlite", "database" },
    { "sqlite3", "database" },
    { "sss", "postcss" },
    { "stencil.config.js", "stencil" },
    { "stencil.config.ts", "stencil" },
    { "stitches.config.js", "stitches" },
    { "stitches.config.ts", "stitches" },
    { "stl", "3d" },
    { "storage.rules", "firebase" },
    { "stories.js", "storybook" },
    { "stories.jsx", "storybook" },
    { "stories.mdx", "storybook" },
    { "stories.svelte", "storybook-svelte" },
    { "stories.ts", "storybook" },
    { "stories.tsx", "storybook" },
    { "stories.vue", "storybook-vue" },
    { "story.js", "storybook" },
    { "story.jsx", "storybook" },
    { "story.mdx", "storybook" },
    { "story.svelte", "storybook-svelte" },
    { "story.ts", "storybook" },
    { "story.tsx", "storybook" },
    { "story.vue", "storybook-vue" },
    { "sty", "latex" },
    { "stylelint.config.cjs", "stylelint" },
    { "stylelint.config.cts", "stylelint" },
    { "stylelint.config.js", "stylelint" },
    { "stylelint.config.mjs", "stylelint" },
    { "stylelint.config.mts", "stylelint" },
    { "stylelint.config.ts", "stylelint" },
    { "stylua.toml", "stylua" },
    { "sublime-project", "sublime" },
    { "sublime-workspace", "sublime" },
    { "sui", "font" },
    { "suit", "font" },
    { "suo", "visual-studio" },
    { "sv", "verilog" },
    { "svelte", "svelte" },
    { "svelte.config.cjs", "svelte-config" },
    { "svelte.config.js", "svelte-config" },
    { "svelte.config.mjs", "svelte-config" },
    { "svelte.config.ts", "svelte-config" },
    { "svg", "svg" },
    { "svh", "verilog" },
    { "swift", "swift" },
    { "t", "perl" },
    { "tailwind.config.cjs", "tailwind" },
    { "tailwind.config.cts", "tailwind" },
    { "tailwind.config.js", "tailwind" },
    { "tailwind.config.mjs", "tailwind" },
    { "tailwind.config.mts", "tailwind" },
    { "tailwind.config.ts", "tailwind" },
    { "tailwind.js", "tailwind" },
    { "tailwind.ts", "tailwind" },
    { "tape", "vhs" },
    { "tar", "zip" },
    { "taskfile.dist.yaml", "taskfile" },
    { "taskfile.dist.yml", "taskfile" },
    { "taskfile.yaml", "taskfile" },
    { "taskfile.yml", "taskfile" },
    { "tauri", "tauri" },
    { "tauri.conf.json", "tauri" },
    { "tauri.conf.json5", "tauri" },
    { "tauri.config.json", "tauri" },
    { "tauri.linux.conf.json", "tauri" },
    { "tauri.macos.conf.json", "tauri" },
    { "tauri.windows.conf.json", "tauri" },
    { "tbz", "zip" },
    { "tbz2", "zip" },
    { "tcc", "cpp-header" },
    { "tcsh", "bash" },
    { "templ", "go-template" },
    { "tesc", "shader" },
    { "tesc.glsl", "shader" },
    { "tese", "shader" },
    { "tese.glsl", "shader" },
    { "tess.hlsl", "shader" },
    { "tessellation.hlsl", "shader" },
    { "test-d.ts", "typescript-test" },
    { "test.cjs", "javascript-test" },
    { "test.cts", "typescript-test" },
    { "test.js", "javascript-test" },
    { "test.jsx", "javascript-test" },
    { "test.lua", "lua-test" },
    { "test.luau", "luau-test" },
    { "test.mjs", "javascript-test" },
    { "test.mts", "typescript-test" },
    { "test.ts", "typescript-test" },
    { "test.tsx", "typescript-test" },
    { "tex", "latex" },
    { "tf", "terraform" },
    { "tf.json", "terraform" },
    { "tfbackend", "terraform" },
    { "tfstate", "terraform" },
    { "tfvars", "terraform" },
    { "tga", "image" },
    { "tgz", "zip" },
    { "thrift", "apache" },
    { "tif", "image" },
    { "tiff", "image" },
    { "tmLanguage", "xml" },
    { "tmpl", "go-template" },
    { "todo", "todo" },
    { "todo.md", "todo" },
    { "todos.md", "todo" },
    { "tofu", "opentofu" },
    { "tofu.json", "opentofu" },
    { "toml", "toml" },
    { "tres", "godot-assets" },
    { "ts", "typescript" },
    { "ts.glsl", "shader" },
    { "ts.snap", "typescript-test" },
    { "tsbuildinfo", "json" },
    { "tscn", "godot-assets" },
    { "tsconfig.app.json", "typescript-config" },
    { "tsconfig.base.json", "typescript-config" },
    { "tsconfig.build.json", "typescript-config" },
    { "tsconfig.cjs.json", "typescript-config" },
    { "tsconfig.components.json", "typescript-config" },
    { "tsconfig.config.json", "typescript-config" },
    { "tsconfig.cypress-ct.json", "typescript-config" },
    { "tsconfig.doc.json", "typescript-config" },
    { "tsconfig.e2e.json", "typescript-config" },
    { "tsconfig.editor.json", "typescript-config" },
    { "tsconfig.eslint.json", "typescript-config" },
    { "tsconfig.esm.json", "typescript-config" },
    { "tsconfig.json", "typescript-config" },
    { "tsconfig.lib.json", "typescript-config" },
    { "tsconfig.lib.prod.json", "typescript-config" },
    { "tsconfig.main.json", "typescript-config" },
    { "tsconfig.mjs.json", "typescript-config" },
    { "tsconfig.node.json", "typescript-config" },
    { "tsconfig.paths.json", "typescript-config" },
    { "tsconfig.spec.json", "typescript-config" },
    { "tsconfig.test.json", "typescript-config" },
    { "tsconfig.vitest.json", "typescript-config" },
    { "tsconfig.web.json", "typescript-config" },
    { "tsconfig.webworker.json", "typescript-config" },
    { "tsconfig.worker.json", "typescript-config" },
    { "tsv", "csv" },
    { "tsx", "typescript-react" },
    { "tsx.snap", "typescript-test" },
    { "ttc", "font" },
    { "ttf", "font" },
    { "turbo.json", "turbo" },
    { "tw", "twine" },
    { "twee", "twine" },
    { "twig", "twig" },
    { "txt", "text" },
    { "typ", "typst" },
    { "typst.toml", "typst" },
    { "u3d", "3d" },
    { "unity", "unity" },
    { "unlicence", "license" },
    { "unlicense", "license" },
    { "uno.config.js", "unocss" },
    { "uno.config.mjs", "unocss" },
    { "uno.config.mts", "unocss" },
    { "uno.config.ts", "unocss" },
    { "unocss.config.js", "unocss" },
    { "unocss.config.mjs", "unocss" },
    { "unocss.config.mts", "unocss" },
    { "unocss.config.ts", "unocss" },
    { "update", "bash" },
    { "url", "url" },
    { "usd", "3d" },
    { "uv.lock", "uv" },
    { "v", "v" },
    { "v.mod", "v" },
    { "vala", "vala" },
    { "vapi", "vapi" },
    { "vb", "visual-studio" },
    { "vbhtml", "razor" },
    { "vbproj", "visual-studio" },
    { "vbproj.user", "visual-studio" },
    { "vbs", "visual-studio" },
    { "vcxitems", "visual-studio" },
    { "vcxitems.filters", "visual-studio" },
    { "vcxproj", "visual-studio" },
    { "vcxproj.filters", "visual-studio" },
    { "vercel.json", "vercel" },
    { "vert", "shader" },
    { "vert.glsl", "shader" },
    { "vertex.glsl", "shader" },
    { "vertexshader", "shader" },
    { "vhd", "verilog" },
    { "vim", "vim" },
    { "viminfo", "vim" },
    { "vimrc", "vim" },
    { "vital", "vital" },
    { "vitalbank", "vital" },
    { "vitallfo", "vital" },
    { "vitalskin", "vital" },
    { "vitaltable", "vital" },
    { "vitaltheme", "vital" },
    { "vite.config.cjs", "vite" },
    { "vite.config.cts", "vite" },
    { "vite.config.js", "vite" },
    { "vite.config.mjs", "vite" },
    { "vite.config.mts", "vite" },
    { "vite.config.ts", "vite" },
    { "vitest.config.cjs", "vitest" },
    { "vitest.config.cts", "vitest" },
    { "vitest.config.js", "vitest" },
    { "vitest.config.mjs", "vitest" },
    { "vitest.config.mts", "vitest" },
    { "vitest.config.ts", "vitest" },
    { "vitest.workspace.js", "vitest" },
    { "vitest.workspace.json", "vitest" },
    { "vitest.workspace.ts", "vitest" },
    { "vob", "video" },
    { "vpkg.json", "v" },
    { "vs.glsl", "shader" },
    { "vsix", "vscode" },
    { "vsixmanifest", "vscode" },
    { "vto", "vento" },
    { "vue", "vue" },
    { "vue.config.cjs", "vue-config" },
    { "vue.config.cts", "vue-config" },
    { "vue.config.js", "vue-config" },
    { "vue.config.mjs", "vue-config" },
    { "vue.config.mts", "vue-config" },
    { "vue.config.ts", "vue-config" },
    { "wally.lock", "wally" },
    { "wally.toml", "wally" },
    { "wasm", "web-assembly" },
    { "wat", "web-assembly" },
    { "wav", "audio" },
    { "webm", "video" },
    { "webmanifest", "json" },
    { "webp", "image" },
    { "webpack.base.cjs", "webpack" },
    { "webpack.base.cts", "webpack" },
    { "webpack.base.js", "webpack" },
    { "webpack.base.mjs", "webpack" },
    { "webpack.base.mts", "webpack" },
    { "webpack.base.ts", "webpack" },
    { "webpack.cjs", "webpack" },
    { "webpack.client.cjs", "webpack" },
    { "webpack.client.cts", "webpack" },
    { "webpack.client.js", "webpack" },
    { "webpack.client.mjs", "webpack" },
    { "webpack.client.mts", "webpack" },
    { "webpack.client.ts", "webpack" },
    { "webpack.common.cjs", "webpack" },
    { "webpack.common.cts", "webpack" },
    { "webpack.common.js", "webpack" },
    { "webpack.common.mjs", "webpack" },
    { "webpack.common.mts", "webpack" },
    { "webpack.common.ts", "webpack" },
    { "webpack.config.babel.js", "webpack" },
    { "webpack.config.babel.ts", "webpack" },
    { "webpack.config.base.babel.js", "webpack" },
    { "webpack.config.base.babel.ts", "webpack" },
    { "webpack.config.base.cjs", "webpack" },
    { "webpack.config.base.cts", "webpack" },
    { "webpack.config.base.js", "webpack" },
    { "webpack.config.base.mjs", "webpack" },
    { "webpack.config.base.mts", "webpack" },
    { "webpack.config.base.ts", "webpack" },
    { "webpack.config.cjs", "webpack" },
    { "webpack.config.client.cjs", "webpack" },
    { "webpack.config.client.cts", "webpack" },
    { "webpack.config.client.js", "webpack" },
    { "webpack.config.client.mjs", "webpack" },
    { "webpack.config.client.mts", "webpack" },
    { "webpack.config.client.ts", "webpack" },
    { "webpack.config.coffee", "webpack" },
    { "webpack.config.common.babel.js", "webpack" },
    { "webpack.config.common.babel.ts", "webpack" },
    { "webpack.config.common.cjs", "webpack" },
    { "webpack.config.common.cts", "webpack" },
    { "webpack.config.common.js", "webpack" },
    { "webpack.config.common.mjs", "webpack" },
    { "webpack.config.common.mts", "webpack" },
    { "webpack.config.common.ts", "webpack" },
    { "webpack.config.cts", "webpack" },
    { "webpack.config.dev.babel.js", "webpack" },
    { "webpack.config.dev.babel.ts", "webpack" },
    { "webpack.config.dev.cjs", "webpack" },
    { "webpack.config.dev.cts", "webpack" },
    { "webpack.config.dev.js", "webpack" },
    { "webpack.config.dev.mjs", "webpack" },
    { "webpack.config.dev.mts", "webpack" },
    { "webpack.config.dev.ts", "webpack" },
    { "webpack.config.js", "webpack" },
    { "webpack.config.main.js", "webpack" },
    { "webpack.config.mjs", "webpack" },
    { "webpack.config.mts", "webpack" },
    { "webpack.config.prod.babel.cjs", "webpack" },
    { "webpack.config.prod.babel.cts", "webpack" },
    { "webpack.config.prod.babel.js", "webpack" },
    { "webpack.config.prod.babel.mjs", "webpack" },
    { "webpack.config.prod.babel.mts", "webpack" },
    { "webpack.config.prod.babel.ts", "webpack" },
    { "webpack.config.prod.cjs", "webpack" },
    { "webpack.config.prod.cts", "webpack" },
    { "webpack.config.prod.js", "webpack" },
    { "webpack.config.prod.mjs", "webpack" },
    { "webpack.config.prod.mts", "webpack" },
    { "webpack.config.prod.ts", "webpack" },
    { "webpack.config.production.babel.js", "webpack" },
    { "webpack.config.production.babel.ts", "webpack" },
    { "webpack.config.production.cjs", "webpack" },
    { "webpack.config.production.cts", "webpack" },
    { "webpack.config.production.js", "webpack" },
    { "webpack.config.production.mjs", "webpack" },
    { "webpack.config.production.mts", "webpack" },
    { "webpack.config.production.ts", "webpack" },
    { "webpack.config.renderer.ts", "webpack" },
    { "webpack.config.server.cjs", "webpack" },
    { "webpack.config.server.cts", "webpack" },
    { "webpack.config.server.js", "webpack" },
    { "webpack.config.server.mjs", "webpack" },
    { "webpack.config.server.mts", "webpack" },
    { "webpack.config.server.ts", "webpack" },
    { "webpack.config.staging.babel.js", "webpack" },
    { "webpack.config.staging.babel.ts", "webpack" },
    { "webpack.config.staging.cjs", "webpack" },
    { "webpack.config.staging.cts", "webpack" },
    { "webpack.config.staging.js", "webpack" },
    { "webpack.config.staging.mjs", "webpack" },
    { "webpack.config.staging.mts", "webpack" },
    { "webpack.config.staging.ts", "webpack" },
    { "webpack.config.test.cjs", "webpack" },
    { "webpack.config.test.cts", "webpack" },
    { "webpack.config.test.js", "webpack" },
    { "webpack.config.test.mjs", "webpack" },
    { "webpack.config.test.mts", "webpack" },
    { "webpack.config.test.ts", "webpack" },
    { "webpack.config.ts", "webpack" },
    { "webpack.config.vendor.cjs", "webpack" },
    { "webpack.config.vendor.cts", "webpack" },
    { "webpack.config.vendor.js", "webpack" },
    { "webpack.config.vendor.mjs", "webpack" },
    { "webpack.config.vendor.mts", "webpack" },
    { "webpack.config.vendor.production.cjs", "webpack" },
    { "webpack.config.vendor.production.cts", "webpack" },
    { "webpack.config.vendor.production.js", "webpack" },
    { "webpack.config.vendor.production.mjs", "webpack" },
    { "webpack.config.vendor.production.mts", "webpack" },
    { "webpack.config.vendor.production.ts", "webpack" },
    { "webpack.config.vendor.ts", "webpack" },
    { "webpack.cts", "webpack" },
    { "webpack.dev.cjs", "webpack" },
    { "webpack.dev.cts", "webpack" },
    { "webpack.dev.js", "webpack" },
    { "webpack.dev.mjs", "webpack" },
    { "webpack.dev.mts", "webpack" },
    { "webpack.dev.ts", "webpack" },
    { "webpack.development.cjs", "webpack" },
    { "webpack.development.cts", "webpack" },
    { "webpack.development.js", "webpack" },
    { "webpack.development.mjs", "webpack" },
    { "webpack.development.mts", "webpack" },
    { "webpack.development.ts", "webpack" },
    { "webpack.dist.cjs", "webpack" },
    { "webpack.dist.cts", "webpack" },
    { "webpack.dist.js", "webpack" },
    { "webpack.dist.mjs", "webpack" },
    { "webpack.dist.mts", "webpack" },
    { "webpack.dist.ts", "webpack" },
    { "webpack.js", "webpack" },
    { "webpack.mix.cjs", "webpack" },
    { "webpack.mix.cts", "webpack" },
    { "webpack.mix.js", "webpack" },
    { "webpack.mix.mjs", "webpack" },
    { "webpack.mix.mts", "webpack" },
    { "webpack.mix.ts", "webpack" },
    { "webpack.mjs", "webpack" },
    { "webpack.mts", "webpack" },
    { "webpack.prod.cjs", "webpack" },
    { "webpack.prod.config.cjs", "webpack" },
    { "webpack.prod.config.cts", "webpack" },
    { "webpack.prod.config.js", "webpack" },
    { "webpack.prod.config.mjs", "webpack" },
    { "webpack.prod.config.mts", "webpack" },
    { "webpack.prod.config.ts", "webpack" },
    { "webpack.prod.cts", "webpack" },
    { "webpack.prod.js", "webpack" },
    { "webpack.prod.mjs", "webpack" },
    { "webpack.prod.mts", "webpack" },
    { "webpack.prod.ts", "webpack" },
    { "webpack.production.cjs", "webpack" },
    { "webpack.production.cts", "webpack" },
    { "webpack.production.js", "webpack" },
    { "webpack.production.mjs", "webpack" },
    { "webpack.production.mts", "webpack" },
    { "webpack.production.ts", "webpack" },
    { "webpack.server.cjs", "webpack" },
    { "webpack.server.cts", "webpack" },
    { "webpack.server.js", "webpack" },
    { "webpack.server.mjs", "webpack" },
    { "webpack.server.mts", "webpack" },
    { "webpack.server.ts", "webpack" },
    { "webpack.test.cjs", "webpack" },
    { "webpack.test.cts", "webpack" },
    { "webpack.test.js", "webpack" },
    { "webpack.test.mjs", "webpack" },
    { "webpack.test.mts", "webpack" },
    { "webpack.test.ts", "webpack" },
    { "webpack.ts", "webpack" },
    { "webpackfile.cjs", "webpack" },
    { "webpackfile.cts", "webpack" },
    { "webpackfile.js", "webpack" },
    { "webpackfile.mjs", "webpack" },
    { "webpackfile.mts", "webpack" },
    { "webpackfile.ts", "webpack" },
    { "wgsl", "shader" },
    { "windi", "windi" },
    { "windi.config.cjs", "windi" },
    { "windi.config.cts", "windi" },
    { "windi.config.js", "windi" },
    { "windi.config.json", "windi" },
    { "windi.config.ts", "windi" },
    { "wma", "audio" },
    { "wmv", "video" },
    { "woff", "font" },
    { "woff2", "font" },
    { "workflows/yaml", "workflow" },
    { "workflows/yml", "workflow" },
    { "wrangler.json", "wrangler" },
    { "wrangler.jsonc", "wrangler" },
    { "wrangler.toml", "wrangler" },
    { "wrap", "meson" },
    { "wv", "audio" },
    { "wxt.config.js", "wxt" },
    { "wxt.config.ts", "wxt" },
    { "xaml", "xaml" },
    { "xcf", "image" },
    { "xcsettings", "xcode" },
    { "xcworkspacedata", "xcode" },
    { "xd", "adobe-xd" },
    { "xhtml", "html" },
    { "xls", "ms-excel" },
    { "xlsb", "ms-excel" },
    { "xlsm", "ms-excel" },
    { "xlsx", "ms-excel" },
    { "xlt", "ms-excel" },
    { "xltm", "ms-excel" },
    { "xltx", "ms-excel" },
    { "xmake.lua", "xmake" },
    { "xml", "xml" },
    { "xml.dist", "xml" },
    { "xml.dist.sample", "xml" },
    { "xquery", "xml" },
    { "xsd", "xml" },
    { "xsl", "xml" },
    { "xslt", "xml" },
    { "xz", "zip" },
    { "yaml", "yaml" },
    { "yarn-error.log", "yarn" },
    { "yarn.config.cjs", "yarn" },
    { "yarn.lock", "yarn-lock" },
    { "yml", "yaml" },
    { "yuv", "video" },
    { "z", "zip" },
    { "zap", "zap" },
    { "zig", "zig" },
    { "zip", "zip" },
    { "zon", "zig" },
    { "zpaq", "zip" },
    { "zsh", "bash" },
    { "zst", "zip" },
};
static const int zc_suffixes_n = 1806;

static const ZcIconDir zc_dirs[] = {
    { ".aws", "folder_aws", "folder_aws_open" },
    { ".azure-devops", "folder_azure-devops", "folder_azure-devops_open" },
    { ".azure-pipelines", "folder_azure-pipelines", "folder_azure-pipelines_open" },
    { ".azuredevops", "folder_azure-devops", "folder_azure-devops_open" },
    { ".cache", "folder_temp", "folder_temp_open" },
    { ".caddy", "folder_caddy", "folder_caddy_open" },
    { ".caddyfiles", "folder_caddy", "folder_caddy_open" },
    { ".cargo", "folder_cargo", "folder_cargo_open" },
    { ".ci", "folder_workflows", "folder_workflows_open" },
    { ".circleci", "folder_circle-ci", "folder_circle-ci_open" },
    { ".config", "folder_config", "folder_config_open" },
    { ".cursor", "folder_cursor", "folder_cursor_open" },
    { ".cypress", "folder_cypress", "folder_cypress_open" },
    { ".devcontainer", "folder_devcontainer", "folder_devcontainer_open" },
    { ".direnv", "folder_direnv", "folder_direnv_open" },
    { ".docker", "folder_docker", "folder_docker_open" },
    { ".fastlane", "folder_fastlane", "folder_fastlane_open" },
    { ".firebase", "folder_firebase", "folder_firebase_open" },
    { ".forgejo", "folder_forgejo", "folder_forgejo_open" },
    { ".fvm", "folder_fvm", "folder_fvm_open" },
    { ".git", "folder_git", "folder_git_open" },
    { ".githooks", "folder_git", "folder_git_open" },
    { ".github", "folder_github", "folder_github_open" },
    { ".gitlab", "folder_gitlab", "folder_gitlab_open" },
    { ".gradle", "folder_gradle", "folder_gradle_open" },
    { ".husky", "folder_husky", "folder_husky_open" },
    { ".idea", "folder_intellij", "folder_intellij_open" },
    { ".k8s", "folder_kubernetes", "folder_kubernetes_open" },
    { ".kubernetes", "folder_kubernetes", "folder_kubernetes_open" },
    { ".lib", "folder_lib", "folder_lib_open" },
    { ".libraries", "folder_lib", "folder_lib_open" },
    { ".library", "folder_lib", "folder_lib_open" },
    { ".libs", "folder_lib", "folder_lib_open" },
    { ".moon", "folder_moonrepo", "folder_moonrepo_open" },
    { ".next", "folder_next", "folder_next_open" },
    { ".now", "folder_vercel", "folder_vercel_open" },
    { ".nuxt", "folder_nuxt", "folder_nuxt_open" },
    { ".nyc-output", "folder_coverage", "folder_coverage_open" },
    { ".nyc_output", "folder_coverage", "folder_coverage_open" },
    { ".output", "folder_dist", "folder_dist_open" },
    { ".pesde", "folder_pesde", "folder_pesde_open" },
    { ".renovate", "folder_renovate", "folder_renovate_open" },
    { ".setting", "folder_config", "folder_config_open" },
    { ".settings", "folder_config", "folder_config_open" },
    { ".storybook", "folder_storybook", "folder_storybook_open" },
    { ".submodules", "folder_git", "folder_git_open" },
    { ".temp", "folder_temp", "folder_temp_open" },
    { ".tmp", "folder_temp", "folder_temp_open" },
    { ".turbo", "folder_turbo", "folder_turbo_open" },
    { ".tx", "folder_locales", "folder_locales_open" },
    { ".vercel", "folder_vercel", "folder_vercel_open" },
    { ".vscode", "folder_vscode", "folder_vscode_open" },
    { ".vscode-test", "folder_vscode", "folder_vscode_open" },
    { ".wxt", "folder_wxt", "folder_wxt_open" },
    { ".xmake", "folder_xmake", "folder_xmake_open" },
    { ".yarn", "folder_yarn", "folder_yarn_open" },
    { "@types", "folder_types", "folder_types_open" },
    { "META-INF", "folder_config", "folder_config_open" },
    { "__fixtures__", "folder_tests", "folder_tests_open" },
    { "__integration-test__", "folder_coverage", "folder_coverage_open" },
    { "__integration-tests__", "folder_coverage", "folder_coverage_open" },
    { "__mocks__", "folder_tests", "folder_tests_open" },
    { "__snapshots__", "folder_tests", "folder_tests_open" },
    { "__stories__", "folder_storybook", "folder_storybook_open" },
    { "__test__", "folder_tests", "folder_tests_open" },
    { "__tests__", "folder_tests", "folder_tests_open" },
    { "_data", "folder_database", "folder_database_open" },
    { "_draft", "folder_mocks", "folder_mocks_open" },
    { "_drafts", "folder_mocks", "folder_mocks_open" },
    { "_image", "folder_images", "folder_images_open" },
    { "_images", "folder_images", "folder_images_open" },
    { "_img", "folder_images", "folder_images_open" },
    { "_imgs", "folder_images", "folder_images_open" },
    { "_layouts", "folder_layouts", "folder_layouts_open" },
    { "_plugins", "folder_plugins", "folder_plugins_open" },
    { "_post", "folder_docs", "folder_docs_open" },
    { "_posts", "folder_docs", "folder_docs_open" },
    { "_sass", "folder_sass", "folder_sass_open" },
    { "_scss", "folder_sass", "folder_sass_open" },
    { "_site", "folder_public", "folder_public_open" },
    { "addon", "folder_plugins", "folder_plugins_open" },
    { "addons", "folder_plugins", "folder_plugins_open" },
    { "admin", "folder_admin", "folder_admin_open" },
    { "admins", "folder_admin", "folder_admin_open" },
    { "android", "folder_android", "folder_android_open" },
    { "anim", "folder_animation", "folder_animation_open" },
    { "animated", "folder_animation", "folder_animation_open" },
    { "animation", "folder_animation", "folder_animation_open" },
    { "animations", "folder_animation", "folder_animation_open" },
    { "anims", "folder_animation", "folder_animation_open" },
    { "api", "folder_api", "folder_api_open" },
    { "apis", "folder_api", "folder_api_open" },
    { "app", "folder_app", "folder_app_open" },
    { "apps", "folder_app", "folder_app_open" },
    { "article", "folder_docs", "folder_docs_open" },
    { "articles", "folder_docs", "folder_docs_open" },
    { "asset", "folder_assets", "folder_assets_open" },
    { "assets", "folder_assets", "folder_assets_open" },
    { "aud", "folder_audio", "folder_audio_open" },
    { "audio", "folder_audio", "folder_audio_open" },
    { "audios", "folder_audio", "folder_audio_open" },
    { "audit", "folder_audit", "folder_audit_open" },
    { "audits", "folder_audit", "folder_audit_open" },
    { "auds", "folder_audio", "folder_audio_open" },
    { "aws", "folder_aws", "folder_aws_open" },
    { "backend", "folder_server", "folder_server_open" },
    { "bench", "folder_benchmark", "folder_benchmark_open" },
    { "benches", "folder_benchmark", "folder_benchmark_open" },
    { "benchmark", "folder_benchmark", "folder_benchmark_open" },
    { "benchmarks", "folder_benchmark", "folder_benchmark_open" },
    { "bin", "folder_dist", "folder_dist_open" },
    { "browser", "folder_public", "folder_public_open" },
    { "browsers", "folder_public", "folder_public_open" },
    { "build", "folder_dist", "folder_dist_open" },
    { "bull", "folder_queue", "folder_queue_open" },
    { "cache", "folder_temp", "folder_temp_open" },
    { "cached", "folder_temp", "folder_temp_open" },
    { "caddy", "folder_caddy", "folder_caddy_open" },
    { "caddyfiles", "folder_caddy", "folder_caddy_open" },
    { "calc", "folder_functions", "folder_functions_open" },
    { "calcs", "folder_functions", "folder_functions_open" },
    { "calculation", "folder_functions", "folder_functions_open" },
    { "calculations", "folder_functions", "folder_functions_open" },
    { "cfg", "folder_config", "folder_config_open" },
    { "cfgs", "folder_config", "folder_config_open" },
    { "ci", "folder_workflows", "folder_workflows_open" },
    { "cli", "folder_command", "folder_command_open" },
    { "client", "folder_client", "folder_client_open" },
    { "clients", "folder_client", "folder_client_open" },
    { "clis", "folder_command", "folder_command_open" },
    { "cloud", "folder_cloud", "folder_cloud_open" },
    { "cmd", "folder_command", "folder_command_open" },
    { "code", "folder_src", "folder_src_open" },
    { "command", "folder_command", "folder_command_open" },
    { "commands", "folder_command", "folder_command_open" },
    { "components", "folder_components", "folder_components_open" },
    { "composable", "folder_composables", "folder_composables_open" },
    { "composables", "folder_composables", "folder_composables_open" },
    { "concept", "folder_mocks", "folder_mocks_open" },
    { "concepts", "folder_mocks", "folder_mocks_open" },
    { "conf", "folder_config", "folder_config_open" },
    { "config", "folder_config", "folder_config_open" },
    { "configs", "folder_config", "folder_config_open" },
    { "configuration", "folder_config", "folder_config_open" },
    { "configurations", "folder_config", "folder_config_open" },
    { "confs", "folder_config", "folder_config_open" },
    { "connection", "folder_connection", "folder_connection_open" },
    { "connections", "folder_connection", "folder_connection_open" },
    { "constant", "folder_constant", "folder_constant_open" },
    { "constants", "folder_constant", "folder_constant_open" },
    { "content", "folder_content", "folder_content_open" },
    { "contents", "folder_content", "folder_content_open" },
    { "controller", "folder_controllers", "folder_controllers_open" },
    { "controllers", "folder_controllers", "folder_controllers_open" },
    { "core", "folder_core", "folder_core_open" },
    { "coverage", "folder_coverage", "folder_coverage_open" },
    { "crate", "folder_packages", "folder_packages_open" },
    { "crates", "folder_packages", "folder_packages_open" },
    { "css", "folder_styles", "folder_styles_open" },
    { "cypress", "folder_cypress", "folder_cypress_open" },
    { "data", "folder_database", "folder_database_open" },
    { "database", "folder_database", "folder_database_open" },
    { "databases", "folder_database", "folder_database_open" },
    { "db", "folder_database", "folder_database_open" },
    { "debug", "folder_debug", "folder_debug_open" },
    { "debugging", "folder_debug", "folder_debug_open" },
    { "demo", "folder_examples", "folder_examples_open" },
    { "demos", "folder_examples", "folder_examples_open" },
    { "dist", "folder_dist", "folder_dist_open" },
    { "dist-newstyle", "folder_dist", "folder_dist_open" },
    { "doc", "folder_docs", "folder_docs_open" },
    { "docker", "folder_docker", "folder_docker_open" },
    { "dockerfiles", "folder_docker", "folder_docker_open" },
    { "docs", "folder_docs", "folder_docs_open" },
    { "document", "folder_docs", "folder_docs_open" },
    { "documentation", "folder_docs", "folder_docs_open" },
    { "documents", "folder_docs", "folder_docs_open" },
    { "download", "folder_download", "folder_download_open" },
    { "downloads", "folder_download", "folder_download_open" },
    { "draft", "folder_mocks", "folder_mocks_open" },
    { "drafts", "folder_mocks", "folder_mocks_open" },
    { "drizzle", "folder_drizzle-orm", "folder_drizzle-orm_open" },
    { "e2e", "folder_coverage", "folder_coverage_open" },
    { "example", "folder_examples", "folder_examples_open" },
    { "examples", "folder_examples", "folder_examples_open" },
    { "extension", "folder_plugins", "folder_plugins_open" },
    { "extensions", "folder_plugins", "folder_plugins_open" },
    { "fastlane", "folder_fastlane", "folder_fastlane_open" },
    { "fig", "folder_images", "folder_images_open" },
    { "figs", "folder_images", "folder_images_open" },
    { "figure", "folder_images", "folder_images_open" },
    { "figures", "folder_images", "folder_images_open" },
    { "firebase", "folder_firebase", "folder_firebase_open" },
    { "fixture", "folder_mocks", "folder_mocks_open" },
    { "fixtures", "folder_mocks", "folder_mocks_open" },
    { "font", "folder_fonts", "folder_fonts_open" },
    { "fonts", "folder_fonts", "folder_fonts_open" },
    { "fragments", "folder_components", "folder_components_open" },
    { "frontend", "folder_client", "folder_client_open" },
    { "frontends", "folder_client", "folder_client_open" },
    { "func", "folder_functions", "folder_functions_open" },
    { "funcs", "folder_functions", "folder_functions_open" },
    { "function", "folder_functions", "folder_functions_open" },
    { "functions", "folder_functions", "folder_functions_open" },
    { "githooks", "folder_git", "folder_git_open" },
    { "github", "folder_github", "folder_github_open" },
    { "gql", "folder_graphql", "folder_graphql_open" },
    { "gradle", "folder_gradle", "folder_gradle_open" },
    { "graphql", "folder_graphql", "folder_graphql_open" },
    { "handler", "folder_controllers", "folder_controllers_open" },
    { "handlers", "folder_controllers", "folder_controllers_open" },
    { "hook", "folder_hooks", "folder_hooks_open" },
    { "hooks", "folder_hooks", "folder_hooks_open" },
    { "html", "folder_views", "folder_views_open" },
    { "husky", "folder_husky", "folder_husky_open" },
    { "i18n", "folder_locales", "folder_locales_open" },
    { "ico", "folder_images", "folder_images_open" },
    { "icon", "folder_images", "folder_images_open" },
    { "icons", "folder_images", "folder_images_open" },
    { "icos", "folder_images", "folder_images_open" },
    { "image", "folder_images", "folder_images_open" },
    { "images", "folder_images", "folder_images_open" },
    { "img", "folder_images", "folder_images_open" },
    { "imgs", "folder_images", "folder_images_open" },
    { "include", "folder_include", "folder_include_open" },
    { "includes", "folder_include", "folder_include_open" },
    { "integration", "folder_connection", "folder_connection_open" },
    { "integration-test", "folder_coverage", "folder_coverage_open" },
    { "integration-tests", "folder_coverage", "folder_coverage_open" },
    { "integrations", "folder_connection", "folder_connection_open" },
    { "internationalization", "folder_locales", "folder_locales_open" },
    { "it", "folder_coverage", "folder_coverage_open" },
    { "javascript", "folder_javascript", "folder_javascript_open" },
    { "js", "folder_javascript", "folder_javascript_open" },
    { "k8s", "folder_kubernetes", "folder_kubernetes_open" },
    { "kubernetes", "folder_kubernetes", "folder_kubernetes_open" },
    { "l10n", "folder_locales", "folder_locales_open" },
    { "lambda", "folder_functions", "folder_functions_open" },
    { "lambdas", "folder_functions", "folder_functions_open" },
    { "lang", "folder_locales", "folder_locales_open" },
    { "langs", "folder_locales", "folder_locales_open" },
    { "language", "folder_locales", "folder_locales_open" },
    { "languages", "folder_locales", "folder_locales_open" },
    { "layout", "folder_layouts", "folder_layouts_open" },
    { "layouts", "folder_layouts", "folder_layouts_open" },
    { "lib", "folder_lib", "folder_lib_open" },
    { "libraries", "folder_lib", "folder_lib_open" },
    { "library", "folder_lib", "folder_lib_open" },
    { "libs", "folder_lib", "folder_lib_open" },
    { "linux", "folder_linux", "folder_linux_open" },
    { "locale", "folder_locales", "folder_locales_open" },
    { "locales", "folder_locales", "folder_locales_open" },
    { "localization", "folder_locales", "folder_locales_open" },
    { "logic", "folder_functions", "folder_functions_open" },
    { "luau_packages", "folder_luau", "folder_luau_open" },
    { "lune_packages", "folder_lune", "folder_lune_open" },
    { "mac", "folder_macos", "folder_macos_open" },
    { "macos", "folder_macos", "folder_macos_open" },
    { "manager", "folder_admin", "folder_admin_open" },
    { "managers", "folder_admin", "folder_admin_open" },
    { "math", "folder_functions", "folder_functions_open" },
    { "maths", "folder_functions", "folder_functions_open" },
    { "measure", "folder_benchmark", "folder_benchmark_open" },
    { "measurement", "folder_benchmark", "folder_benchmark_open" },
    { "measures", "folder_benchmark", "folder_benchmark_open" },
    { "message", "folder_messages", "folder_messages_open" },
    { "messages", "folder_messages", "folder_messages_open" },
    { "middleware", "folder_middleware", "folder_middleware_open" },
    { "middlewares", "folder_middleware", "folder_middleware_open" },
    { "mock", "folder_mocks", "folder_mocks_open" },
    { "mocks", "folder_mocks", "folder_mocks_open" },
    { "mod", "folder_plugins", "folder_plugins_open" },
    { "modding", "folder_plugins", "folder_plugins_open" },
    { "moderator", "folder_admin", "folder_admin_open" },
    { "moderators", "folder_admin", "folder_admin_open" },
    { "mods", "folder_plugins", "folder_plugins_open" },
    { "module", "folder_plugins", "folder_plugins_open" },
    { "modules", "folder_plugins", "folder_plugins_open" },
    { "movie", "folder_video", "folder_video_open" },
    { "movies", "folder_video", "folder_video_open" },
    { "mq", "folder_queue", "folder_queue_open" },
    { "music", "folder_audio", "folder_audio_open" },
    { "nix", "folder_nix", "folder_nix_open" },
    { "node_modules", "folder_node", "folder_node_open" },
    { "now", "folder_vercel", "folder_vercel_open" },
    { "nuxt", "folder_nuxt", "folder_nuxt_open" },
    { "option", "folder_config", "folder_config_open" },
    { "options", "folder_config", "folder_config_open" },
    { "out", "folder_dist", "folder_dist_open" },
    { "package", "folder_packages", "folder_packages_open" },
    { "packages", "folder_packages", "folder_packages_open" },
    { "page", "folder_views", "folder_views_open" },
    { "pages", "folder_views", "folder_views_open" },
    { "patches", "folder_git", "folder_git_open" },
    { "performance", "folder_benchmark", "folder_benchmark_open" },
    { "pesde", "folder_pesde", "folder_pesde_open" },
    { "photo", "folder_images", "folder_images_open" },
    { "photograph", "folder_images", "folder_images_open" },
    { "photographs", "folder_images", "folder_images_open" },
    { "photos", "folder_images", "folder_images_open" },
    { "pic", "folder_images", "folder_images_open" },
    { "pics", "folder_images", "folder_images_open" },
    { "picture", "folder_images", "folder_images_open" },
    { "pictures", "folder_images", "folder_images_open" },
    { "pkg", "folder_packages", "folder_packages_open" },
    { "pkgs", "folder_packages", "folder_packages_open" },
    { "plugin", "folder_plugins", "folder_plugins_open" },
    { "plugins", "folder_plugins", "folder_plugins_open" },
    { "post", "folder_docs", "folder_docs_open" },
    { "posts", "folder_docs", "folder_docs_open" },
    { "pre-commit-channel", "folder_pre-commit", "folder_pre-commit_open" },
    { "prisma", "folder_prisma", "folder_prisma_open" },
    { "private", "folder_private", "folder_private_open" },
    { "proto", "folder_proto", "folder_proto_open" },
    { "protobuf", "folder_proto", "folder_proto_open" },
    { "protobufs", "folder_proto", "folder_proto_open" },
    { "protos", "folder_proto", "folder_proto_open" },
    { "provider", "folder_controllers", "folder_controllers_open" },
    { "providers", "folder_controllers", "folder_controllers_open" },
    { "public", "folder_public", "folder_public_open" },
    { "public_html", "folder_views", "folder_views_open" },
    { "pwa", "folder_client", "folder_client_open" },
    { "queue", "folder_queue", "folder_queue_open" },
    { "queues", "folder_queue", "folder_queue_open" },
    { "redux", "folder_redux", "folder_redux_open" },
    { "release", "folder_dist", "folder_dist_open" },
    { "renovate", "folder_renovate", "folder_renovate_open" },
    { "restapi", "folder_api", "folder_api_open" },
    { "roblox_packages", "folder_roblox", "folder_roblox_open" },
    { "roblox_server_packages", "folder_roblox", "folder_roblox_open" },
    { "router", "folder_routes", "folder_routes_open" },
    { "routers", "folder_routes", "folder_routes_open" },
    { "routes", "folder_routes", "folder_routes_open" },
    { "sample", "folder_examples", "folder_examples_open" },
    { "sample-data", "folder_examples", "folder_examples_open" },
    { "samples", "folder_examples", "folder_examples_open" },
    { "sass", "folder_sass", "folder_sass_open" },
    { "screen", "folder_views", "folder_views_open" },
    { "screengrab", "folder_images", "folder_images_open" },
    { "screengrabs", "folder_images", "folder_images_open" },
    { "screens", "folder_views", "folder_views_open" },
    { "screenshot", "folder_images", "folder_images_open" },
    { "screenshots", "folder_images", "folder_images_open" },
    { "script", "folder_scripts", "folder_scripts_open" },
    { "scripting", "folder_scripts", "folder_scripts_open" },
    { "scripts", "folder_scripts", "folder_scripts_open" },
    { "scss", "folder_sass", "folder_sass_open" },
    { "security", "folder_security", "folder_security_open" },
    { "server", "folder_server", "folder_server_open" },
    { "servers", "folder_server", "folder_server_open" },
    { "service", "folder_controllers", "folder_controllers_open" },
    { "services", "folder_controllers", "folder_controllers_open" },
    { "setting", "folder_config", "folder_config_open" },
    { "settings", "folder_config", "folder_config_open" },
    { "share", "folder_shared", "folder_shared_open" },
    { "shared", "folder_shared", "folder_shared_open" },
    { "site", "folder_public", "folder_public_open" },
    { "sketch", "folder_mocks", "folder_mocks_open" },
    { "sketches", "folder_mocks", "folder_mocks_open" },
    { "sound", "folder_audio", "folder_audio_open" },
    { "sounds", "folder_audio", "folder_audio_open" },
    { "source", "folder_src", "folder_src_open" },
    { "sources", "folder_src", "folder_src_open" },
    { "spec", "folder_tests", "folder_tests_open" },
    { "specs", "folder_tests", "folder_tests_open" },
    { "sql", "folder_database", "folder_database_open" },
    { "src", "folder_src", "folder_src_open" },
    { "src-tauri", "folder_tauri", "folder_tauri_open" },
    { "srcs", "folder_src", "folder_src_open" },
    { "stories", "folder_storybook", "folder_storybook_open" },
    { "storybook", "folder_storybook", "folder_storybook_open" },
    { "style", "folder_styles", "folder_styles_open" },
    { "styles", "folder_styles", "folder_styles_open" },
    { "stylesheet", "folder_styles", "folder_styles_open" },
    { "stylesheets", "folder_styles", "folder_styles_open" },
    { "submodules", "folder_git", "folder_git_open" },
    { "svg", "folder_svg", "folder_svg_open" },
    { "svgs", "folder_svg", "folder_svg_open" },
    { "temp", "folder_temp", "folder_temp_open" },
    { "template", "folder_templates", "folder_templates_open" },
    { "templates", "folder_templates", "folder_templates_open" },
    { "test", "folder_tests", "folder_tests_open" },
    { "testing", "folder_tests", "folder_tests_open" },
    { "tests", "folder_tests", "folder_tests_open" },
    { "theme", "folder_themes", "folder_themes_open" },
    { "themes", "folder_themes", "folder_themes_open" },
    { "tmp", "folder_temp", "folder_temp_open" },
    { "translate", "folder_locales", "folder_locales_open" },
    { "translation", "folder_locales", "folder_locales_open" },
    { "translations", "folder_locales", "folder_locales_open" },
    { "trigger", "folder_hooks", "folder_hooks_open" },
    { "triggers", "folder_hooks", "folder_hooks_open" },
    { "types", "folder_types", "folder_types_open" },
    { "typings", "folder_types", "folder_types_open" },
    { "upload", "folder_upload", "folder_upload_open" },
    { "uploads", "folder_upload", "folder_upload_open" },
    { "util", "folder_utils", "folder_utils_open" },
    { "utilities", "folder_utils", "folder_utils_open" },
    { "utility", "folder_utils", "folder_utils_open" },
    { "utils", "folder_utils", "folder_utils_open" },
    { "vercel", "folder_vercel", "folder_vercel_open" },
    { "vid", "folder_video", "folder_video_open" },
    { "video", "folder_video", "folder_video_open" },
    { "videos", "folder_video", "folder_video_open" },
    { "vids", "folder_video", "folder_video_open" },
    { "view", "folder_views", "folder_views_open" },
    { "views", "folder_views", "folder_views_open" },
    { "web", "folder_public", "folder_public_open" },
    { "website", "folder_public", "folder_public_open" },
    { "widget", "folder_components", "folder_components_open" },
    { "widgets", "folder_components", "folder_components_open" },
    { "windows", "folder_windows", "folder_windows_open" },
    { "workflow", "folder_workflows", "folder_workflows_open" },
    { "workflows", "folder_workflows", "folder_workflows_open" },
    { "www", "folder_public", "folder_public_open" },
    { "wwwroot", "folder_public", "folder_public_open" },
    { "xcodeproj", "folder_xcode", "folder_xcode_open" },
    { "xcschemes", "folder_xcode", "folder_xcode_open" },
    { "xcshareddata", "folder_xcode", "folder_xcode_open" },
    { "xcworkspace", "folder_xcode", "folder_xcode_open" },
    { "xmake", "folder_xmake", "folder_xmake_open" },
};
static const int zc_dirs_n = 421;

#endif
